package com.junar.searchbenzine.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.junar.searchbenzine.Benzine;

import com.junar.searchbenzine.dao.BenzineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig benzineDaoConfig;

    private final BenzineDao benzineDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type,
            Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
        super(db);

        benzineDaoConfig = daoConfigMap.get(BenzineDao.class).clone();
        benzineDaoConfig.initIdentityScope(type);
        benzineDao = new BenzineDao(benzineDaoConfig, this);
        registerDao(Benzine.class, benzineDao);
    }

    public void clear() {
        benzineDaoConfig.getIdentityScope().clear();
    }

    public BenzineDao getBenzineDao() {
        return benzineDao;
    }
}
